name: tool
publish_to: 'none'

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  linter:
  analyzer:
#  analyzer: ^7.1.0
  dio: ^5.7.0
  yaml: ^3.1.3
  yaml_edit: ^2.2.2
#  _fe_analyzer_shared: ^78.0.0

#  linter:
#    path: ../../../../shared/svm/flutter/default/bin/cache/dart-sdk/lib/
#    sdk: dart

dependency_overrides:
  linter:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/linter
      ref: 3.6.0
  analyzer:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/analyzer
      ref: 3.6.0
  _fe_analyzer_shared:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/_fe_analyzer_shared
      ref: 3.6.0
